#!/bin/bash
set -eo pipefail

NUM_GPUS="${NUM_GPUS:-8}"


fabric run --strategy ddp --devices "${NUM_GPUS}" --precision bf16-mixed train.py --config config/fineweb/1B/nextlat_finewebedu_1b_100b_horizon2.yaml trainer.experiment_name="NextLat-1B-horizon2"
torchrun --nproc_per_node="${NUM_GPUS}" eval/eval_checkpoints.py --train_config config/fineweb/1B/nextlat_finewebedu_1b_100b_horizon2.yaml --checkpoint_dir "data/nextlat-finewebedu/NextLat-1B-horizon2-seed1234" --eval_config config/fineweb/lm_eval_fineweb.yaml --last_checkpoint_only --wandb_project fineweb-lmeval
python3 -m pip install -q "datasets==4.6.1"
torchrun --nproc_per_node="${NUM_GPUS}" eval/eval_speculative_checkpoints.py --train_config config/fineweb/1B/nextlat_finewebedu_1b_100b_horizon2.yaml --checkpoint_dir "data/nextlat-finewebedu/NextLat-1B-horizon2-seed1234" --last_checkpoint_only --num_samples_per_dataset 1024 --prompt_tokens 512 --max_new_tokens 512 --gamma 2 --top_k 1 --output_dir output/speculative_eval/nextlat-h2-finewebedu-g2 --wandb_project finewebspec --wandb_run_name nextlat-h2-finewebedu-spec-g2 --wandb_tags speculative,decoding,finewebedu,nextlat,gamma2
torchrun --nproc_per_node="${NUM_GPUS}" eval/eval_speculative_checkpoints.py --train_config config/fineweb/1B/nextlat_finewebedu_1b_100b_horizon2.yaml --checkpoint_dir "data/nextlat-finewebedu/NextLat-1B-horizon2-seed1234" --last_checkpoint_only --num_samples_per_dataset 1024 --prompt_tokens 512 --max_new_tokens 512 --gamma 3 --top_k 1 --output_dir output/speculative_eval/nextlat-h2-finewebedu-g3 --wandb_project finewebspec --wandb_run_name nextlat-h2-finewebedu-spec-g3 --wandb_tags speculative,decoding,finewebedu,nextlat,gamma3
torchrun --nproc_per_node="${NUM_GPUS}" eval/eval_speculative_checkpoints.py --train_config config/fineweb/1B/nextlat_finewebedu_1b_100b_horizon2.yaml --checkpoint_dir "data/nextlat-finewebedu/NextLat-1B-horizon2-seed1234" --last_checkpoint_only --num_samples_per_dataset 1024 --prompt_tokens 512 --max_new_tokens 512 --gamma 4 --top_k 1 --output_dir output/speculative_eval/nextlat-h2-finewebedu-g4 --wandb_project finewebspec --wandb_run_name nextlat-h2-finewebedu-spec-g4 --wandb_tags speculative,decoding,finewebedu,nextlat,gamma4
torchrun --nproc_per_node="${NUM_GPUS}" eval/eval_speculative_checkpoints.py --train_config config/fineweb/1B/nextlat_finewebedu_1b_100b_horizon2.yaml --checkpoint_dir "data/nextlat-finewebedu/NextLat-1B-horizon2-seed1234" --last_checkpoint_only --num_samples_per_dataset 1024 --prompt_tokens 512 --max_new_tokens 512 --gamma 5 --top_k 1 --output_dir output/speculative_eval/nextlat-h2-finewebedu-g5 --wandb_project finewebspec --wandb_run_name nextlat-h2-finewebedu-spec-g5 --wandb_tags speculative,decoding,finewebedu,nextlat,gamma5
torchrun --nproc_per_node="${NUM_GPUS}" eval/eval_speculative_checkpoints.py --train_config config/fineweb/1B/nextlat_finewebedu_1b_100b_horizon2.yaml --checkpoint_dir "data/nextlat-finewebedu/NextLat-1B-horizon2-seed1234" --last_checkpoint_only --num_samples_per_dataset 1024 --prompt_tokens 512 --max_new_tokens 512 --gamma 6 --top_k 1 --output_dir output/speculative_eval/nextlat-h2-finewebedu-g6 --wandb_project finewebspec --wandb_run_name nextlat-h2-finewebedu-spec-g6 --wandb_tags speculative,decoding,finewebedu,nextlat,gamma6
torchrun --nproc_per_node="${NUM_GPUS}" eval/eval_speculative_checkpoints.py --train_config config/fineweb/1B/nextlat_finewebedu_1b_100b_horizon2.yaml --checkpoint_dir "data/nextlat-finewebedu/NextLat-1B-horizon2-seed1234" --last_checkpoint_only --num_samples_per_dataset 1024 --prompt_tokens 512 --max_new_tokens 512 --gamma 7 --top_k 1 --output_dir output/speculative_eval/nextlat-h2-finewebedu-g7 --wandb_project finewebspec --wandb_run_name nextlat-h2-finewebedu-spec-g7 --wandb_tags speculative,decoding,finewebedu,nextlat,gamma7
torchrun --nproc_per_node="${NUM_GPUS}" eval/eval_speculative_checkpoints.py --train_config config/fineweb/1B/nextlat_finewebedu_1b_100b_horizon2.yaml --checkpoint_dir "data/nextlat-finewebedu/NextLat-1B-horizon2-seed1234" --last_checkpoint_only --num_samples_per_dataset 1024 --prompt_tokens 512 --max_new_tokens 512 --gamma 8 --top_k 1 --output_dir output/speculative_eval/nextlat-h2-finewebedu-g8 --wandb_project finewebspec --wandb_run_name nextlat-h2-finewebedu-spec-g8 --wandb_tags speculative,decoding,finewebedu,nextlat,gamma8
torchrun --nproc_per_node="${NUM_GPUS}" eval/eval_speculative_checkpoints.py --train_config config/fineweb/1B/nextlat_finewebedu_1b_100b_horizon2.yaml --checkpoint_dir "data/nextlat-finewebedu/NextLat-1B-horizon2-seed1234" --last_checkpoint_only --num_samples_per_dataset 1024 --prompt_tokens 512 --max_new_tokens 512 --gamma 9 --top_k 1 --output_dir output/speculative_eval/nextlat-h2-finewebedu-g9 --wandb_project finewebspec --wandb_run_name nextlat-h2-finewebedu-spec-g9 --wandb_tags speculative,decoding,finewebedu,nextlat,gamma9
torchrun --nproc_per_node="${NUM_GPUS}" eval/eval_speculative_checkpoints.py --train_config config/fineweb/1B/nextlat_finewebedu_1b_100b_horizon2.yaml --checkpoint_dir "data/nextlat-finewebedu/NextLat-1B-horizon2-seed1234" --last_checkpoint_only --num_samples_per_dataset 1024 --prompt_tokens 512 --max_new_tokens 512 --gamma 10 --top_k 1 --output_dir output/speculative_eval/nextlat-h2-finewebedu-g10 --wandb_project finewebspec --wandb_run_name nextlat-h2-finewebedu-spec-g10 --wandb_tags speculative,decoding,finewebedu,nextlat,gamma10
