# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

patch_size: 8
dim: 768
layers: 12

block_config:
  - type: model.SelfAttention
    length_dim: l
    params:
      head_dim: 64
      use_qk_norm: true
  - type: lact_ttt.FastWeightGluMLPMultihead
    length_dim: vl
    params:
      head_dim: 768 # 256
      inter_multi: 1
      base_lr: 0.01
      muon_update_steps: 5
      ttt_loss_type: dot_product
      no_query: false
  - type: model.MLP
    length_dim: vl
    params:
      inter_multi: 4