# default use GPT (all other models are false)
use_bst: false
use_nextlat: false
use_mtp_gloeckle: false
use_mtp_jtp: false

seed: 1234

trainer:
  train_batches: 600000
  val_batches: 128
  val_only: false
  log_interval: 10
  val_interval: 2000

  # Checkpointing
  # Save checkpoint after latest validation step
  save_last_checkpoint: true
  # Save checkpoint after validation step with lowest loss
  save_best_checkpoint: true
  # Keep all checkpoints
  always_save_checkpoint: false
  # Save checkpoint every N training steps
  save_recovery_checkpoint: -1
  # Always keep checkpoints at these steps
  # Must be multiples of val_interval
  keep_checkpoint_steps: []
  out_dir: out
  # "scratch" or "resume"
  init_from: scratch

  # Logging
  log_to_file: true
  log_to_wandb: true
  wandb_project: tinystories

  # Enable deterministic CUDA algorithms for reproducibility (slower)
  deterministic: false
  # Compile model with torch.compile
  compile: true
  # Use fused kernels
  use_fused_kernels: false
  # Garbage collect after every N steps
  garbage_collect: -1

  # AR
  sampling_mode: AR

  # Speculative sampling
  speculative_gamma: 4
  top_p: null

  # Whether to train a probe
  train_probe: false

  # Wandb tags
  wandb_tags: []
data:
  # Name of the datamodule to use
  dataset: tinystories
  # Total batch size per gradient update
  effective_batch_size: 256
  # Number of forward/backward passes to accumulate
  gradient_accum_steps: 1
  # Batch size to process BST pairs
  # This is independent of all other batch sizes
  pair_batch_size: 32768
  # Number of worker processes for dataloader
  num_workers: 0

  # For tinystories fill in middle only
  goal_range: [25, 75]

  # Huggingface repo name or file path to load the tokenizer used
  tokenizer_name_or_path: ""
  # Fallback if tokenizer_name_or_path is not specified
  tokenizer_eos_id: -1

  # For stargraph only
  stargraph_data_path: ""
  stargraph_max_nodes: 50

model:
  n_layer: 8
  n_head: 8
  n_embd: 768
  dropout: 0.0
  bias: false
  # Total number of tokens in the vocabulary
  vocab_size: 1000
  # This is the actual context length of the model
  block_size: 256
  # This is a prefix for stargraph
  context_length: 0

  # BST specific options
  # Min and max gap between two tokens in a pair
  bst_pair_minimum_gap: 1
  bst_pair_maximum_gap: -1
  # Probability used to randomly subsample pairs
  # If 1.0, then train on all pairs
  bst_pair_subsample_rate: 1.0
  # What to predict for gap size 1: "next_token" or "eos"
  bst_single_gap_prediction_mode: eos

  # GPT specific options
  # "next_token" or "fim"
  gpt_mode: next_token

  # Whether to compute hidden state effective rank
  compute_hidden_state_rank: false

  # NextLat defaults
  lambda_kl: 1.0
  lambda_mse: 1.0
  lambda_ce: 0.0
  mtp_horizon: 1
  proj_factor: 1.0

optimizer:
  optimizer_type: adam # options: adam, muon
  mu: 0.95
  nesterov: true
  learning_rate: 0.0003
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  adjust_lr_fn: null

lr_scheduler:
  schedule: constant
  warmup_iters: 0
  warmdown_iters: 0